vich_uploader:
    db_driver: orm

    mappings:
        employee_image:
            uri_prefix: /images/employee
            upload_destination: '%kernel.project_dir%/public/images/employee'
        citizen_image:
            uri_prefix: /images/citizen
            upload_destination: '%kernel.project_dir%/public/images/citizen'
