<?php

namespace App\Controller\Admin;

use App\Entity\Employee;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\KeyValueStore;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\EmailField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TelephoneField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Vich\UploaderBundle\Form\Type\VichImageType;

class EmployeeCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Employee::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud->showEntityActionsAsDropdown();
    }

//    public function createIndexQueryBuilder(SearchDto $searchDto, EntityDto $entityDto, FieldCollection $fields, FilterCollection $filters): QueryBuilder
//    {
//        $qb = parent::createIndexQueryBuilder($searchDto, $entityDto, $fields, $filters);
//
//        dump($qb);
//        exit();
//        if (array_key_exists('ROLE_ADMIN', $context->getEntity()->getInstance()->getUser()->getRoles()) && $this->isGranted('ROLE_ADMIN')) {
//            return $qb;
//        }
//
//        $qb->leftJoin('entity.user', 'u')
//            ->Where('u.roles NOT LIKE :role')
//            ->setParameter('role', '%ROLE_ADMIN%');
//        return $qb;
//    }
//    public function index(AdminContext $context)
//    {
//        dump($context->get);
//        exit();
//        return parent::index($context); // TODO: Change the autogenerated stub
//    }


//    public function createEditFormBuilder(EntityDto $entityDto, KeyValueStore $formOptions, AdminContext $context): FormBuilderInterface
//    {
////        dump($entityDto);
////        exit();
//        $result = parent::createEditFormBuilder($entityDto, $formOptions, $context); // TODO: Change the autogenerated stub
//        if (array_key_exists('ROLE_ADMIN', $entityDto->getInstance()->getUser()->getRoles()) & $this->isGranted('ROLE_ADMIN')) {
//            return $result;
//        }
//        $this->denyAccessUnlessGranted('ROLE_ADMIN');
////        throw new AccessDeniedException();
//    }

//    public function edit(AdminContext $context)
//    {
////        dump(array_key_exists('ROLE_ADMIN', $context->getEntity()->getInstance()->getUser()->getRoles()));
////        exit();
//        $result = parent::edit($context); // TODO: Change the autogenerated stub
//        if (array_key_exists('ROLE_ADMIN', $context->getEntity()->getInstance()->getUser()->getRoles()) && $this->isGranted('ROLE_ADMIN')) {
//            return $result;
//        }
//        return $result
//    }

//    public function createEditForm(EntityDto $entityDto, KeyValueStore $formOptions, AdminContext $context): FormInterface
//    {
//        $result = parent::createEditForm($entityDto, $formOptions, $context); // TODO: Change the autogenerated stub
//        if (array_key_exists('ROLE_ADMIN', $entityDto->getInstance()->getUser()->getRoles()) && $this->isGranted('ROLE_ADMIN')) {
//            throw new AccessDeniedException();
//        }
//        return $result;
//    }

    public function configureResponseParameters(KeyValueStore $responseParameters): KeyValueStore
    {
        foreach ($responseParameters->get('entities') as $entity) {
            if ($entity->getInstance()->getUser()) {
                if (['ROLE_ADMIN'] == $entity->getInstance()->getUser()->getRoles()) {
//                    $a = new ArrayCollection();
//                    $a->new($entity->getActions()[0]);
//                    $entity->setActions($a);
                    $entity->getActions()->offsetUnset(1);
                    $entity->getActions()->offsetUnset(2);
                }
            }
        }
        return parent::configureResponseParameters($responseParameters); // TODO: Change the autogenerated stub
    }

    public function configureActions(Actions $actions): Actions
    {
        $actions->add(Crud::PAGE_INDEX, Action::DETAIL)
            ->reorder(Crud::PAGE_INDEX, [Action::DETAIL, Action::EDIT, Action::DELETE]);
        if ($this->isGranted('ROLE_ADMIN')) {
            $actions->setPermissions([Action::NEW => 'ROLE_ADMIN', Action::EDIT, 'ROLE_ADMIN', Action::DELETE, 'ROLE_ADMIN']);
        } elseif ($this->isGranted('ROLE_MANGER')) {
            $actions->setPermissions([Action::NEW => 'ROLE_ADMIN', Action::EDIT, 'ROLE_ADMIN', Action::DELETE, 'ROLE_ADMIN']);
        }
        return $actions;
    }

    public function configureFields(string $pageName): iterable
    {
        $imgFile = ImageField::new('thumbnailFile')->setFormType(VichImageType::class)->setLabel('Avatar');
        $imgName = ImageField::new('thumbnail')->setBasePath('/images/employee/')->setLabel('Avatar');
        if ($pageName == Crud::PAGE_INDEX) {
            yield IntegerField::new('id');
        }
        yield TextField::new('firstName');
        yield TextField::new('lastName');
        yield TelephoneField::new('phone');
        if ($pageName == Crud::PAGE_DETAIL | $pageName == Crud::PAGE_INDEX) {
            yield EmailField::new('user.email')->setLabel('Email');
            yield $imgName;
        } else {
            yield $imgFile;
        }
//        yield ChoiceField::new('user.roles')->setChoices(['Admin' => "ROLE_ADMIN", 'Manager' => 'ROLE_MANAGER', 'Staff' => 'ROLE_STAFF'])->hideOnForm()->setLabel('Role')->setFormTypeOptionIfNotSet();
    }
}
